import time
def intro():
    print("")
    print("   SSSSSSSSSSSSSSS                                        iiii                    lllllll        CCCCCCCCCCCCChhhhhhh                                  ffffffffffffffff    ffffffffffffffff  ")
    print(" SS:::::::::::::::S                                      i::::i                   l:::::l     CCC::::::::::::Ch:::::h                                 f::::::::::::::::f  f::::::::::::::::f ")
    print("S:::::SSSSSS::::::S                                       iiii                    l:::::l   CC:::::::::::::::Ch:::::h                                f::::::::::::::::::ff::::::::::::::::::f")
    print("S:::::S     SSSSSSS                                                               l:::::l  C:::::CCCCCCCC::::Ch:::::h                                f::::::fffffff:::::ff::::::fffffff:::::f")
    print("S:::::S               ooooooooooo       cccccccccccccccciiiiiii   aaaaaaaaaaaaa    l::::l C:::::C       CCCCCC h::::h hhhhh         aaaaaaaaaaaaa    f:::::f       fffffff:::::f       ffffff")
    print("S:::::S             oo:::::::::::oo   cc:::::::::::::::ci:::::i   a::::::::::::a   l::::lC:::::C               h::::hh:::::hhh      a::::::::::::a   f:::::f             f:::::f             ")
    print(" S::::SSSS         o:::::::::::::::o c:::::::::::::::::c i::::i   aaaaaaaaa:::::a  l::::lC:::::C               h::::::::::::::hh    aaaaaaaaa:::::a f:::::::ffffff      f:::::::ffffff       ")
    print("  SS::::::SSSSS    o:::::ooooo:::::oc:::::::cccccc:::::c i::::i            a::::a  l::::lC:::::C               h:::::::hhh::::::h            a::::a f::::::::::::f      f::::::::::::f       ")
    print("    SSS::::::::SS  o::::o     o::::oc::::::c     ccccccc i::::i     aaaaaaa:::::a  l::::lC:::::C               h::::::h   h::::::h    aaaaaaa:::::a f::::::::::::f      f::::::::::::f       ")
    print("       SSSSSS::::S o::::o     o::::oc:::::c              i::::i   aa::::::::::::a  l::::lC:::::C               h:::::h     h:::::h  aa::::::::::::a f:::::::ffffff      f:::::::ffffff       ")
    print("            S:::::So::::o     o::::oc:::::c              i::::i  a::::aaaa::::::a  l::::lC:::::C               h:::::h     h:::::h a::::aaaa::::::a  f:::::f             f:::::f             ")
    print("            S:::::So::::o     o::::oc::::::c     ccccccc i::::i a::::a    a:::::a  l::::l C:::::C       CCCCCC h:::::h     h:::::ha::::a    a:::::a  f:::::f             f:::::f             ")
    print("SSSSSSS     S:::::So:::::ooooo:::::oc:::::::cccccc:::::ci::::::ia::::a    a:::::a l::::::l C:::::CCCCCCCC::::C h:::::h     h:::::ha::::a    a:::::a f:::::::f           f:::::::f            ")
    print("S::::::SSSSSS:::::So:::::::::::::::o c:::::::::::::::::ci::::::ia:::::aaaa::::::a l::::::l  CC:::::::::::::::C h:::::h     h:::::ha:::::aaaa::::::a f:::::::f           f:::::::f            ")
    print("S:::::::::::::::SS  oo:::::::::::oo   cc:::::::::::::::ci::::::i a::::::::::aa:::al::::::l    CCC::::::::::::C h:::::h     h:::::h a::::::::::aa:::af:::::::f           f:::::::f            ")
    print(" SSSSSSSSSSSSSSS      ooooooooooo       cccccccccccccccciiiiiiii  aaaaaaaaaa  aaaallllllll       CCCCCCCCCCCCC hhhhhhh     hhhhhhh  aaaaaaaaaa  aaaafffffffff           fffffffff ")
    print("")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    time.sleep(0.1)
    print(".")
    print("")
